name: github_tg_crawler

on:
  workflow_dispatch: # 支持手动运行
  schedule:
    - cron: '0 22 * * *' # 北京时间早上6点运行 (UTC 22:00)
  push:
    paths:
      - 'crawler.py'
      - '.github/workflows/crawler.yml'

jobs:
  crawler_job:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run Crawler
        env:
          
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: python crawler.py

      - name: Push Results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Action"
          export TZ='Asia/Shanghai'
          dt=$(date "+%Y-%m-%d %H:%M:%S")
          
          # 检查是否有文件变动
          git add urls.txt subscribes.txt
          if git diff --staged --quiet; then
            echo "没有新数据，跳过推送。"
          else
            git commit -m "Auto update: $(date '+%Y-%m-%d %H:%M:%S')"
            git push
          fi
