name: sub_parser
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */4 * * *'  
  push:
    paths:
      - 'sub_parser.py'
      - '.github/workflows/sub_parser.yml'
      - 'filter_subs.txt'

jobs:
  run-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install aiohttp geoip2 pyyaml

      - name: Run Sub Parser
        run: python sub_parser.py

      - name: Commit and Push
        run: |
          git config --local user.email "GitHub Action"
          git config --local user.name "action@github.com"
          git add sub_parser.txt sub_parser.csv sub_parser_base64.txt sub_parser.yaml
          
          if git diff --cached --quiet; then
            echo "No changes to commit, skipping push."
          else
            export TZ='Asia/Shanghai'
            git commit -m "Update nodes: $(date +'%Y-%m-%d %H:%M:%S')"
            git pull --rebase origin main
            git push origin HEAD:${{ github.ref }}
          fi
